#!/usr/bin/env bash
set -uo pipefail

mkdir -p evidence
evidence_file="evidence/group-a-diagnostics.md"
{
  echo "# Group A Diagnostics Evidence"
  echo
  echo "- Generated at (UTC): $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "- GitHub run: ${GITHUB_RUN_ID:-unavailable}"
  echo "- Repository: ${GITHUB_REPOSITORY:-unavailable}"
  echo
  echo "> This evidence is generated by executing the commands below in GitHub Actions. It does not verify product implementation."
  echo
} > "$evidence_file"

failures=0
check_cmd() {
  local label="$1"
  local command_text="$2"
  local output status result
  output=$(bash -lc "$command_text" 2>&1)
  status=$?
  if [[ "$status" -eq 0 ]]; then result="PASS"; else result="FAIL"; failures=$((failures + 1)); fi
  {
    echo "## $label — $result"
    echo
    echo '**Command**'
    echo '```text'
    echo "$command_text"
    echo '```'
    echo
    echo '**Actual output**'
    echo '```text'
    echo "$output"
    echo '```'
    echo
    echo "Exit code: $status"
    echo
  } >> "$evidence_file"
}

check_cmd "Runner OS" "grep PRETTY_NAME /etc/os-release; uname -a"
check_cmd "Runner architecture" "uname -m; dpkg --print-architecture"
check_cmd "JDK version" "java -version"
check_cmd "Java path" "command -v java; printf 'JAVA_HOME=%s\\n' \"${JAVA_HOME:-}\""
check_cmd "Gradle availability and version" "command -v gradle; gradle --version"
check_cmd "Android SDK location and sdkmanager" "printf 'ANDROID_HOME=%s\\nANDROID_SDK_ROOT=%s\\n' \"${ANDROID_HOME:-}\" \"${ANDROID_SDK_ROOT:-}\"; command -v sdkmanager; sdkmanager --version"
check_cmd "Android SDK platforms" "sdkmanager --list_installed | grep -E 'platforms;android-'"
check_cmd "Android Build Tools" "sdkmanager --list_installed | grep -E 'build-tools;'"
check_cmd "Android Platform Tools" "sdkmanager --list_installed | grep -E 'platform-tools'"
check_cmd "ADB" "command -v adb; adb version"
check_cmd "Git" "command -v git; git --version"
check_cmd "GitHub Actions environment" "printf 'GITHUB_ACTIONS=%s\\nRUNNER_OS=%s\\nRUNNER_ARCH=%s\\nImageVersion=%s\\n' \"${GITHUB_ACTIONS:-}\" \"${RUNNER_OS:-}\" \"${RUNNER_ARCH:-}\" \"${ImageVersion:-}\""
check_cmd "Android/Gradle toolchain compatibility evidence" "java -version; gradle --version; sdkmanager --version; adb version"
check_cmd "Modern Android platform constraints evidence" "sdkmanager --list_installed | grep -E 'platform-tools|platforms;android-35|build-tools;35\\.'"

{
  echo "## Overall result"
  echo
  if [[ "$failures" -eq 0 ]]; then
    echo "**PASS** — all Group A diagnostics completed successfully."
  else
    echo "**FAIL** — $failures diagnostic check(s) failed."
  fi
  echo
  echo "Note: no Android/Gradle application project exists at this checkpoint, so application-specific AGP/Kotlin compilation compatibility is intentionally not claimed."
} >> "$evidence_file"

cat "$evidence_file"
if [[ "$failures" -ne 0 ]]; then exit 1; fi
